url: "https://venkateshcv1809.github.io"
baseurl: ""

# Build settings
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
    smart_quotes: lsquo,rsquo,ldquo,rdquo

sass:
    style: compressed
    sourcemap: development
    quiet_deps: true

collections:
    pages:
        output: true
        permalink: /:name
        is_structural: true

exclude:
    - Gemfile
    - Gemfile.lock
    - .jekyll-cache
    - .justfile
    - justfile
    - mise.lock
    - mise.toml
    - README.md
