collections:
  pages:
    output: true
    permalink: /:name
    is_structural: true

# Sass configuration
sass:
  sass_dir: /assets/css/_sass
  style: compressed
  sourcemap: development
  quiet_deps: true

# Files and directories to exclude from the compiled _site directory
exclude:
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache
  - .justfile
  - justfile
  - mise.lock
  - mise.toml
  - README.md