url: "https://venkateshcv1809.github.io"
baseurl: ""

collections:
  pages:
    output: true
    permalink: /:name
    is_structural: true

sass:
  style: compressed
  sourcemap: development
  quiet_deps: true

exclude:
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache
  - .justfile
  - justfile
  - mise.lock
  - mise.toml
  - README.md