title: VENKATESH C V

description: >
  Personal portfolio, technical blogs, notes, and experiments.

author:
  name: VENKATESH C V

repository:
  url: https://github.com/venkateshcv1809/venkateshcv1809.github.io

copyright:
  owner: VENKATESH C V
  start_year: 2026