github:
  username: venkateshcv1809
  url: https://github.com/venkateshcv1809

linkedin:
  username: venkateshcv1809
  url: https://linkedin.com/in/venkateshcv1809

email:
  address: venkateshvairam@gmail.com